# Generated by Django 4.0.6 on 2022-08-10 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qwitter_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='follow',
            new_name='follows',
        ),
    ]
